<a href="https://colab.research.google.com/github/Vedika-Garg/Python-project-by-Vedika-Garg.ipynb/blob/main/Proj2_vedika_sudoku_solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

class SudokuSolver:
    def __init__(self, board):
        try:
            self.board = np.array(board)
            if self.board.shape != (9, 9):
                raise ValueError("Board must be a 9x9 matrix.")
        except Exception as e:
            print(f"An error occurred while initializing the board: {e}")

    def find_empty_space(self):
        try:
            loc = np.where(self.board == 0)
            if len(loc[0]) > 0:
                return loc[0][0], loc[1][0]
            return None, None
        except Exception as e:
            print(f"An error occurred while finding an empty space: {e}")
            return None, None

    def is_guess_correct(self, guess, row, col):
        try:
            # Check row
            if guess in self.board[row]:
                return False
            # Check column
            if guess in self.board[:, col]:
                return False
            # Check square
            start_row, start_col = 3 * (row // 3), 3 * (col // 3)
            if guess in self.board[start_row:start_row+3, start_col:start_col+3]:
                return False
            return True
        except Exception as e:
            print(f"An error occurred while checking if the guess is correct: {e}")
            return False

    def solve(self):
        try:
            row, col = self.find_empty_space()
            if row is None:  # No empty space left, puzzle solved
                return True

            for guess in range(1, 10):
                if self.is_guess_correct(guess, row, col):
                    self.board[row][col] = guess
                    if self.solve():
                        return True
                    self.board[row][col] = 0  # Reset the guess
            return False
        except Exception as e:
            print(f"An error occurred while solving the Sudoku: {e}")
            return False

# Test the SudokuSolver class with NumPy and exception handling
board = [
    [0,0,0,8,0,0,0,0,9],
    [0,1,9,0,0,5,8,3,0],
    [0,4,3,0,1,0,0,0,7],
    [4,0,0,1,5,0,0,0,3],
    [0,0,2,7,0,4,0,1,0],
    [0,8,0,0,9,0,6,0,0],
    [0,7,0,0,0,6,3,0,0],
    [0,3,0,0,7,0,0,8,0],
    [9,0,4,5,0,0,0,0,1],
]

try:
    solver = SudokuSolver(board)
    if solver.solve():
        print("Sudoku Solved:")
        print(solver.board)
    else:
        print("No solution exists.")
except Exception as e:
    print(f"An error occurred: {e}")


Sudoku Solved:
[[2 5 6 8 3 7 1 4 9]
 [7 1 9 2 4 5 8 3 6]
 [8 4 3 6 1 9 2 5 7]
 [4 6 7 1 5 8 9 2 3]
 [3 9 2 7 6 4 5 1 8]
 [5 8 1 3 9 2 6 7 4]
 [1 7 8 4 2 6 3 9 5]
 [6 3 5 9 7 1 4 8 2]
 [9 2 4 5 8 3 7 6 1]]
